const statNameAPI = {
	gamesPlayed: 'Games',
	pointsForPG: 'Points For Per Game',
	totalYardsOffensePG: 'Total Yards Per Game',
	offensivePlaysPG: 'Offensive Plays Per Game',
	offensiveYardsPP: 'Yards Per Play',
	offensiveTurnoversPG: 'Turnovers Committed Per Game',
	fumblesLostPG: 'Fumbles Lost Per Game',
	firstDownsPG: 'First Downs Per Game',
	passCompPG: 'Pass Comp. Per Game',
	passAttPG: 'Pass Attempts Per Game',
	passYdsPG: 'Passing Yards Per Game',
	passTdPG: 'Passing TDs Per Game',
	offensiveIntPG: 'INTs Thrown Per Game',
	passYdsPerAtt: 'Passing Yards Per Attempt',
	passFirstDownsPG: 'Passing First Downs Per Game',
	rushAttPG: 'Rushing Attempts Per Game',
	rushYdsPG: 'Rushing Yards Per Game',
	rushTdPG: 'Rushing TDs Per Game',
	rushYdsPerAtt: 'Rushing Yards Per Attempt',
	rushFirstDownsPG: 'Rushing First Downs Per Game',
	offensivePenaltiesPG: 'Offensive Penalties Per Game',
	offensivePenaltyYdsPG: 'Offensive Penalty Yards Per Game',
	scoringPctFor: 'Scoring %',
	offensiveTurnoverPct: 'Turnovers Committed %',
	passCompPct: 'Passing Comp. %',
	passTouchdownPct: 'Passing TD %',
	passIntPct: 'Passing INT %',
	passLong: 'Passing Long',
	passYdsPerComp: 'Passing Yards Per Comp.',
	passRating: 'Passer Rating',
	sacksAllowed: 'Sacks Allowed',
	sacksAllowedYds: 'Sack Yards Allowed',
	sackPctOff: 'Sack % Allowed',
	comebacks: 'Comebacks',
	gwd: 'Game-Winning Drives',
	rushLong: 'Rushing Long',
	fumblesAllowed: 'Fumbles Allowed',
	thirdDownPct: '3rd Down %',
	fourthDownPct: '4th Down %',
	redzonePct: 'Redzone %',
	turnoverDiff: 'Turnover Differential',
	pointDiff: 'Point Differential',
	pointsAgPG: 'Points Against Per Game',
	yardsAllowedPG: 'Yards Allowed Per Game',
	defensivePlaysPG: 'Defensive Plays Per Game',
	yardsAllowedPP: 'Yards Allowed Per Play',
	defensiveTurnoversPG: 'Defensive Turnovers Per Game',
	forcedFumblesPG: 'Forced Fumbles Per Game',
	firstDownsAllowedPG: 'First Downs Allowed Per Game',
	passCompAllowedPG: 'Pass Comp. Allowed Per Game',
	passAttAgPG: 'Passes Attempted Against Per Game',
	passTdAllowedPG: 'Passing TDs Allowed Per Game',
	defensiveIntPG: 'INTs Per Game',
	passYdsPerAttAg: 'Passing Yards Per Attempt Against',
	passFistDownsAllowedPG: 'Passing First Downs Allowed Per Game',
	rushAttAgPG: 'Rushing Attempts Against Per Game',
	rushYdsAllowedPG: 'Rushing Yards Allowed Per Game',
	rushTdAllowedPG: 'Rushing TDs Allowed Per Game',
	rushYdsPerAttAg: 'Rushing Yards Per Attempt Against',
	rushFirstDownsAllowedPG: 'Rushing First Downs Allowed Per Game',
	defensivePenaltiesPG: 'Defensive Penalties Per Game',
	defensivePenaltyYdsPG: 'Defensive Penalty Yards Per Game',
	scoringPctAg: 'Scoring % Against',
	defensiveTurnoverPct: 'Defensive Turnover %',
	passCompPctAllowed: 'Passing Comp. % Allowed',
	passTdPctAg: 'Passing TD % Against',
	passesDefensedPG: 'Passes Defensed Per Game',
	defIntPct: 'Defensive INT %',
	passYardsPerAttAg: 'Passing Yards Per Attempt Against',
	passYardsPerCompAllowed: 'Passing Yards Per Comp. Allowed',
	passRatingAg: 'Passer Rating Against',
	sacksPG: 'Defensive Sack %',
	sackYdsPG: 'Defensive Sack Yards Per Game',
	qbHitsPG: 'QB Hits Per Game',
	tacklesForLossPG: 'Tackles For Loss Per Game',
	sackPctDef: 'Defensive Sack %',
	passYdsPGAllowed: 'Passing Yards Per Game Allowed',
	thirdDownPctAg: '3rd Down % Against',
	fourthDownPctAg: '4th Down % Against',
	redzonePctAg: 'Redzone % Against',
	spreads: 'Spread',
	moneyLine: 'Moneyline',
	overUnder: 'Over/Under',
};

export default statNameAPI;
