const statNameAPI = {
	stats: {
		record: 'Record',
		gamesPlayed: 'Games',
		pointsForPG: 'Pts For P/G',
		totalYardsOffensePG: 'Total Yds P/G',
		offensivePlaysPG: 'Off. Plays P/G',
		offensiveYardsPP: 'Yds Per Play',
		offensiveTurnoversPG: 'Off. Turnovers P/G',
		fumblesLostPG: 'Fumbles Lost P/G',
		firstDownsPG: '1st Downs P/G',
		passCompPG: 'Pass Comp. P/G',
		passAttPG: 'Pass Att P/G',
		passYdsPG: 'Pass Yds P/G',
		passTdPG: 'Pass TDs P/G',
		offensiveIntPG: 'Off. INTs P/G',
		passYdsPerAtt: 'Pass Yds Per Att',
		passFirstDownsPG: 'Pass 1st Downs P/G',
		rushAttPG: 'Rush Att P/G',
		rushYdsPG: 'Rush Yds P/G',
		rushTdPG: 'Rush TDs P/G',
		rushYdsPerAtt: 'Rush Yds Per Att',
		rushFirstDownsPG: 'Rush 1st Downs P/G',
		offensivePenaltiesPG: 'Off. Penalties P/G',
		offensivePenaltyYdsPG: 'Off. Penalty Yds P/G',
		scoringPctFor: 'Scoring %',
		offensiveTurnoverPct: 'Off. Turnover %',
		passCompPct: 'Pass Comp. %',
		passTouchdownPct: 'Pass TD %',
		passIntPct: 'Pass INT %',
		passLong: 'Pass Long',
		passYdsPerComp: 'Pass Yds Per Comp.',
		passRating: 'Passer Rating',
		sacksAllowed: 'Sacks Agst',
		sacksAllowedYds: 'Sack Yds Agst',
		sackPctOff: 'Sack % Agst',
		comebacks: 'Comebacks',
		gwd: 'Game-Winning Drives',
		rushLong: 'Rush Long',
		fumblesAllowed: 'Off. Fumbles',
		thirdDownPct: '3rd Down %',
		fourthDownPct: '4th Down %',
		redzonePct: 'Redzone %',
		turnoverDiff: 'Turnover Differential',
		pointDiff: 'Point Differential',
		pointsAgPG: 'Pts Agst P/G',
		yardsAllowedPG: 'Yds Agst P/G',
		defensivePlaysPG: 'Def. Plays P/G',
		yardsAllowedPP: 'Yds Agst Per Play',
		defensiveTurnoversPG: 'Def. Turnovers P/G',
		forcedFumblesPG: 'Forced Fumbles P/G',
		firstDownsAllowedPG: '1st Downs Agst P/G',
		passCompAllowedPG: 'Pass Comp. Agst P/G',
		passAttAgPG: 'Pass Att Agst P/G',
		passTdAllowedPG: 'Pass TDs Agst P/G',
		defensiveIntPG: 'Def. INTs P/G',
		passYdsPerAttAg: 'Pass Yds Per Att Agst',
		passFistDownsAllowedPG: 'Pass 1st Downs Agst P/G',
		rushAttAgPG: 'Rush Att Agst P/G',
		rushYdsAllowedPG: 'Rush Yds Agst P/G',
		rushTdAllowedPG: 'Rush TDs Agst P/G',
		rushYdsPerAttAg: 'Rush Yds Per Att Agst',
		rushFirstDownsAllowedPG: 'Rush 1st Downs Agst P/G',
		defensivePenaltiesPG: 'Def. Penalties P/G',
		defensivePenaltyYdsPG: 'Def. Penalty Yds P/G',
		scoringPctAg: 'Scoring % Agst',
		defensiveTurnoverPct: 'Def. Turnover %',
		passCompPctAllowed: 'Pass Comp. % Agst',
		passTdPctAg: 'Pass TD % Agst',
		passesDefensedPG: 'Passes Defensed P/G',
		defIntPct: 'Def. INT %',
		passYardsPerAttAg: 'Pass Yds Per Att Agst',
		passYardsPerCompAllowed: 'Pass Yds Per Comp. Agst',
		passRatingAg: 'Passer Rating Agst',
		sacksPG: 'Def. Sack %',
		sackYdsPG: 'Def. Sack Yds P/G',
		qbHitsPG: 'Def. QB Hits P/G',
		tacklesForLossPG: 'Tackles For Loss P/G',
		sackPctDef: 'Def. Sack %',
		passYdsPGAllowed: 'Pass Yds P/G Agst',
		thirdDownPctAg: '3rd Down % Agst',
		fourthDownPctAg: '4th Down % Agst',
		redzonePctAg: 'Redzone % Agst',
	},
	betting: {
		spreads: 'Spread',
		moneyLine: 'Moneyline',
		overUnder: 'Over/Under',
	},
	sites: {
		unibet: 'Unibet',
		draftkings: 'DraftKings',
		pointsbetus: 'PointsBet (US)',
		bookmaker: 'Bookmaker',
		mybookieag: 'MyBookie.ag',
		williamhill_us: 'William Hill (US)',
		betrivers: 'BetRivers',
		gtbets: 'GTbets',
		bovada: 'Bovada',
		betonlineag: 'BetOnline.ag',
		lowvig: 'LowVig.ag',
		betfair: 'Betfair',
		intertops: 'Intertops',
	},
};

export default statNameAPI;
